config/routes.rb
Rails.application.routes.draw do
  resources :libros

end

app/models/libro.rb
class Libro
  include Mongoid::Document

  store_in collection: "books"

  field :title, type: String
  field :created, type: String
  field :description, type: String
  field :last_modified, type: String
  field :latest_revision, type: Integer
  field :key, type: String
  field :authors, type: String
  field :type, type: String
  field :subjects, type: Array
  field :revision, type: Integer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: [:show, :edit, :update, :destroy]

  # GET /libros
  # GET /libros.json
  def index
    # @libros = Libro.all
    @libros = Libro.all.order_by({title:0}).limit(100)
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1
  # PATCH/PUT /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro.destroy
    respond_to do |format|
      format.html { redirect_to libros_url, notice: 'Libro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libro_params
      params.require(:libro).permit(:title, :created, :last_modified, :last_modified, :latest_revision, :key, :authors, :type, :subjects, :revision)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookfilm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/libros/_form.html.erb
<%= form_for(@libro) do |f| %>
  <% if @libro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

      <ul>
      <% @libro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :created.type %><br>
    <%= f.text_field :created.type %>
  </div>
  <div class="field">
    <%= f.label :created.value %><br>
    <%= f.datetime_select :created.value %>
  </div>
  <div class="field">
    <%= f.label :last_modified.type %><br>
    <%= f.text_field :last_modified.type %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :last_modified.value %><br>
    <%= f.datetime_select :last_modified.value %>
  </div>
  <div class="field">
    <%= f.label :latest_revision %><br>
    <%= f.number_field :latest_revision %>
  </div>
  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :authors.type.key %><br>
    <%= f.text_field :authors.type.key %>
  </div>
  <div class="field">
    <%= f.label :authors.author.key %><br>
    <%= f.text_field :authors.author.key %>
  </div>
  <div class="field">
    <%= f.label :type.key %><br>
    <%= f.text_field :type.key %>
  </div>
  <div class="field">
    <%= f.label :subjects %><br>
    <%= f.text_field :subjects %>
  </div>
  <div class="field">
    <%= f.label :revision %><br>
    <%= f.number_field :revision %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libros/edit.html.erb
<h1>Editing libro</h1>

<%= render 'form' %>

<%= link_to 'Show', @libro %> |
<%= link_to 'Back', libros_path %>

app/views/libros/index.html.erb
<h1>Listing libros</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Created</th>
      <th>Last modified</th>
      <th>Latest revision</th>
      <th>Key</th>
      <th>Authors</th>
      <th>Type</th>
      <th>Subjects</th>
      <th>Revision</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libros.each do |libro| %>
      <tr>
        <td><%= libro.title %></td>
        <td><%= libro.description %></td>
        <td><%= libro.created %></td>
        <td><%= libro.last_modified %></td>
        <td><%= libro.latest_revision %></td>
        <td><%= libro.key %></td>
        <td><%= libro.authors%></td>
        <td><%= libro.type %></td>
        <td><%= libro.subjects %></td>
        <td><%= libro.revision %></td>
        <td><%= link_to 'Show', libro %></td>
        <td><%= link_to 'Edit', edit_libro_path(libro) %></td>
        <td><%= link_to 'Destroy', libro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Libro', new_libro_path %>

app/views/libros/new.html.erb
<h1>New libro</h1>

<%= render 'form' %>

<%= link_to 'Back', libros_path %>

app/views/libros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @libro.title %>
</p>

<p>
  <strong>Created:</strong>
  <%= @libro.created %>
</p>

<p>
  <strong>Last modified:</strong>
  <%= @libro.last_modified%>
</p>

<p>
  <strong>Last modified:</strong>
  <%= @libro.last_modified %>
</p>

<p>
  <strong>Latest revision:</strong>
  <%= @libro.latest_revision %>
</p>

<p>
  <strong>Key:</strong>
  <%= @libro.key %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @libro.authors %>
</p>

<p>
  <strong>Type:</strong>
  <%= @libro.type %>
</p>

<p>
  <strong>Subjects:</strong>
  <%= @libro.subjects %>
</p>

<p>
  <strong>Revision:</strong>
  <%= @libro.revision %>
</p>

<%= link_to 'Edit', edit_libro_path(@libro) %> |
<%= link_to 'Back', libros_path %>